var username:string = ("Hey Ayesha, I have Started Learning Typescript");
var username1:string = ("Ayesha");
var num1: number =  2;
var num2: number =  4;
var num3: number =  6;
var num4: number =  8;
var num5: number =  10;
var num6: number =  12;
var num7: number =  14;
var num8: number =  16;
var num9: number =  18;
var num10: number = 20;
console.log(username);
console.log(username1);
console.log(num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10);
console.log(num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10);
console.log(num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10);
console.log(num9/num10);
console.log(num1+num2-num4*num5/num8);
